version: '3.1'

services:
  api:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://root:toor@mongo:27017/ChatApp?authSource=admin
      PORT: 8080
      SECRET: MyProductionSecret
      TTL: 7d
    volumes:
      - ./backend/dist:/usr/src/app/dist
      - ./backend/node_modules:/usr/src/app/node_modules
      - ./backend-logs:/usr/src/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
