version: '3.1'

services:
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://root:toor@mongo:27017/ChatApp?authSource=admin
      PORT: 8080
      SECRET: MyProductionSecret
      TTL: 7d
    volumes:
      - ./backend/dist:/usr/src/app/dist
      - ./backend/node_modules:/usr/src/app/node_modules
      - ../backend-logs:/usr/src/app/logs
    depends_on:
      - mongo

  front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
