FROM node:lts-alpine

# Create app directory
WORKDIR /app

# LOGs directory
RUN mkdir logs

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
COPY yarn.lock ./

COPY . ./

RUN yarn install

EXPOSE 8080

CMD [ "yarn", "dev" ]